apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsai-bot.fullname" . }}
  labels:
    {{- include "opsai-bot.labels" . | nindent 4 }}
type: Opaque
data:
  slack-bot-token: {{ .Values.secrets.slack.botToken | b64enc | quote }}
  slack-app-token: {{ .Values.secrets.slack.appToken | b64enc | quote }}
  slack-signing-secret: {{ .Values.secrets.slack.signingSecret | b64enc | quote }}
  grafana-webhook-secret: {{ .Values.secrets.webhook.grafanaSecret | b64enc | quote }}
  alertmanager-webhook-secret: {{ .Values.secrets.webhook.alertmanagerSecret | b64enc | quote }}
